---
title: "main r file"
author: "Julianna Alvord"
date: "2/13/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### This should remain the same for everyone
```{r}
library(dplyr)
library(mosaic)
library(ggplot2)
library(stats)

#can't upload file because too large
#need to select vars

#vars selected and data filtered in other rmd (data download.Rmd)

filtered_data <- read.csv("Pop Health Data 2016 2.csv")
```

###Julianna
```{r}
#Starting data analysis 2-14

#Creating new vars/cleaning------------------------

filtered_data2 <- filtered_data

#Transgender
filtered_data2 <- filtered_data2 %>%
  filter(!trnsgndr %in% c(7,9)) %>%
  mutate(transgender = ifelse(trnsgndr == 1, "female", 
                              ifelse(trnsgndr == 2, "male", 
                                     ifelse(trnsgndr == 3, "non-conforming", "cis"))))

#High HIV risk binary variable 
filtered_data2 <- filtered_data2 %>%
  filter(!is.na(hivrisk4)) %>%
  filter(!hivrisk4 %in% c(7, 9)) %>%
  mutate(high_hiv_risk = ifelse(hivrisk4 == 1, 1, 0))

#Race (grouped) 
filtered_data2 <- filtered_data2 %>%
  mutate(race = ifelse(x.racegr3 == 1, "white", 
                       ifelse(x.racegr3 == 2, "black", 
                              ifelse(x.racegr3 == 3, "other", 
                                     ifelse(x.racegr3 == 4, "multi", 
                                            ifelse(x.racegr3 == 9, NA, "hispanic"))))),
         race_binary = ifelse(x.racegr3 == 1, "white", "racial/ethnic minority"))

filtered_data2$race_binary <- as.factor(filtered_data2$race_binary)
filtered_data2$race_binary <- relevel(filtered_data2$race_binary, ref = "white")

filtered_data2$race <- as.factor(filtered_data2$race)
filtered_data2$race <- relevel(filtered_data2$race, ref = "white")

#Income (binary)
filtered_data2 <- filtered_data2 %>%
  mutate(income_binary = ifelse(income2 %in% c(1, 2, 3, 4), "<25k", 
                                ifelse(income2 %in% c(77, 99), NA, 
                                       ifelse(is.na(income2), NA, ">25k"))))

filtered_data2$income_binary <- as.factor(filtered_data2$income_binary)
filtered_data2$income_binary <- relevel(filtered_data2$income_binary, ref = "<25k")

#Emotional support (categorical)
filtered_data2 <- filtered_data2 %>%
  mutate(em_sup_cat = ifelse(emtsuprt %in% c(7,9), NA, emtsuprt)) %>%
  mutate(em_sup_cat = factor(emtsuprt, levels = c(1,2,3,4,5), labels = c("always", "usually", "sometimes", "rarely", "never")))

filtered_data2$em_sup_cat<- as.factor(filtered_data2$em_sup_cat)
filtered_data2$em_sup_cat <- relevel(filtered_data2$em_sup_cat, ref = "never")

#Education
filtered_data2 <- filtered_data2 %>%
  mutate(edu_binary = ifelse(educa == 6, "college grad", ifelse(educa == 9, NA, "not college grad")))

filtered_data2$edu_binary<- as.factor(filtered_data2$edu_binary)
filtered_data2$edu_binary <- relevel(filtered_data2$edu_binary, ref = "not college grad")

#Age
filtered_data2 <- filtered_data2 %>%
  mutate(age_cat = factor(x.age.g, levels = c(1,2,3,4,5, 6), labels = c("18-24", "25-34", "35-44", "45-54", "55-64", "65+")))

filtered_data2$age_cat<- as.factor(filtered_data2$age_cat)
filtered_data2$age_cat <- relevel(filtered_data2$age_cat, ref = "18-24")

#Heavy Drinker
filtered_data2 <- filtered_data2 %>%
  mutate(heavy_drink = ifelse(x.rfdrhv5 == 1, "not heavy", 
                              ifelse(x.rfdrhv5 == 9, NA, "heavy drinker")))

filtered_data2$heavy_drink<- as.factor(filtered_data2$heavy_drink)
filtered_data2$heavy_drink <- relevel(filtered_data2$heavy_drink, ref = "not heavy")

#Binge Drinker
filtered_data2 <- filtered_data2 %>%
  mutate(binge_drink = ifelse(x.rfbing5 == 1, "not binge", 
                              ifelse(x.rfbing5 == 9, NA, "binge drinker")))

filtered_data2$binge_drink<- as.factor(filtered_data2$binge_drink)
filtered_data2$binge_drink <- relevel(filtered_data2$binge_drink, ref = "not binge")

#Creating unhealthy drink
filtered_data2 <- filtered_data2 %>%
  mutate(unhealthy_drink = ifelse(binge_drink == "binge drinker"|heavy_drink == "heavy drinker", "unhealthy drinker", 
                                  ifelse(is.na(binge_drink)|is.na(heavy_drink), NA, "not unhealthy")))

filtered_data2$unhealthy_drink<- as.factor(filtered_data2$unhealthy_drink)
filtered_data2$unhealthy_drink <- relevel(filtered_data2$unhealthy_drink, ref = "not unhealthy")

#Marital status
filtered_data2 <- filtered_data2 %>%
  mutate(partnered = ifelse(marital %in% c(1,6), "partnered", 
                            ifelse(marital == 9, NA, "not partnered")))

filtered_data2$partnered<- as.factor(filtered_data2$partnered)
filtered_data2$partnered <- relevel(filtered_data2$partnered, ref = "not partnered")


#General Health 
filtered_data2 <- filtered_data2 %>%
  mutate(gen_health = ifelse(genhlth %in% c(7,9), NA, genhlth)) %>%
  mutate(gen_health = factor(genhlth, levels = c(1,2,3,4,5), labels = c("excellent", "very good", "good", "fair", "poor")))

filtered_data2$gen_health<- as.factor(filtered_data2$gen_health)
filtered_data2$gen_health <- relevel(filtered_data2$gen_health, ref = "poor")

#physical health
filtered_data2 <- filtered_data2 %>%
  mutate(physical_health = ifelse(physhlth == 88, 0, 
                                  ifelse(physhlth %in% c(77, 99), NA, physhlth)))

#mental health
filtered_data2 <- filtered_data2 %>%
  mutate(mental_health = ifelse(menthlth == 88, 0, 
                                ifelse(menthlth %in% c(77, 99), NA, menthlth)))

#poor health
filtered_data2 <- filtered_data2 %>%
  mutate(poor_health = ifelse(poorhlth == 88, 0, 
                                ifelse(poorhlth %in% c(77, 99), NA, poorhlth)))

#health plan
filtered_data2 <- filtered_data2 %>%
  mutate(health_plan = ifelse(hlthpln1 == 1, "health care", 
                              ifelse(hlthpln1 %in% c(7,9), NA, "no health care")))

filtered_data2$health_plan<- as.factor(filtered_data2$health_plan)
filtered_data2$health_plan <- relevel(filtered_data2$health_plan, ref = "no health care")

#medical cost
filtered_data2 <- filtered_data2 %>%
  mutate(dr_cost = ifelse(medcost == 1, "could not afford", 
                          ifelse(medcost %in% c(7,9), NA, "always afford")))

filtered_data2$dr_cost<- as.factor(filtered_data2$dr_cost)
filtered_data2$dr_cost <- relevel(filtered_data2$dr_cost, ref = "could not afford")

#routine checkup
filtered_data2 <- filtered_data2 %>%
  mutate(routine_checkup = ifelse(checkup1 == 1, "past year", ifelse(checkup1 == 2, "past 2 years", ifelse(checkup1 == 3, "past 5 years", ifelse(checkup1 == 4, "5 or more years", ifelse(checkup1 %in% c(7,9), NA, "Never"))))))

filtered_data2$routine_checkup<- as.factor(filtered_data2$routine_checkup)
filtered_data2$routine_checkup <- relevel(filtered_data2$routine_checkup, ref = "Never")

#sexual orientation
filtered_data2 <- filtered_data2 %>%
  mutate(sex_orient = ifelse(sxorient %in% c(7,9), NA, sxorient)) %>%
  mutate(sex_orient = factor(sxorient, levels = c(1,2,3,4), labels = c("straight", "lesbian/gay", "bisexual", "other")))

filtered_data2$sex_orient<- as.factor(filtered_data2$sex_orient)
filtered_data2$sex_orient <- relevel(filtered_data2$sex_orient, ref = "straight")

#doctor visits
filtered_data2 <- filtered_data2 %>%
  mutate(dr_visits = ifelse(drvisits == 88, 0, 
                                ifelse(drvisits %in% c(77, 99), NA, drvisits)))

#medication cost
filtered_data2 <- filtered_data2 %>%
  mutate(med_cost = ifelse(medscost == 1, "could not afford",
                           ifelse(medscost == 2, "always afford", NA)))

filtered_data2$med_cost<- as.factor(filtered_data2$med_cost)
filtered_data2$med_cost <- relevel(filtered_data2$med_cost, ref = "could not afford")

#BMI 
filtered_data2 <- filtered_data2 %>%
  mutate(bmi = factor(x.bmi5cat, levels = c(1,2,3,4), labels = c("underweight", "normal", "overweight", "obese")))

filtered_data2$bmi<- as.factor(filtered_data2$bmi)
filtered_data2$bmi <- relevel(filtered_data2$bmi, ref = "normal")

#Smoking
filtered_data2 <- filtered_data2 %>%
  mutate(smoker = ifelse(x.smoker3 == 9, NA,
                         ifelse(x.smoker3 %in% c(1, 2, 3), "has smoked", "never smoked")))

filtered_data2$smoker<- as.factor(filtered_data2$smoker)
filtered_data2$smoker <- relevel(filtered_data2$smoker, ref = "never smoked")

#Descriptive Stats-----------------------
tally(filtered_data2$transgender)
tally(filtered_data2$high_hiv_risk)


#Models-----------------------------------

#simple model
log_simp <- glm(high_hiv_risk ~ transgender, data = filtered_data2, family = binomial)
summary(log_simp)

exp(cbind(OR = coef(log_simp)))

#Adding race var
# logm2 <- glm(high_hiv_risk ~ transgender + race, data = filtered_data2, family = binomial)
# summary(logm2)
# 
# exp(cbind(OR = coef(logm2)))

#Logistic model 
# logm_int <- glm(high_hiv_risk ~ transgender + race_binary + income_binary + edu_binary + em_sup_cat, data = filtered_data2, family = binomial)
# summary(logm_int)
# 
# exp(cbind(OR = coef(logm_int)))

#Risk Difference
RD_crude<- glm(high_hiv_risk ~ transgender, data=filtered_data2, family=gaussian(link="identity"))
summary(RD_crude)
confint(RD_crude)

#Model 1 (Demographics)
logm1 <- glm(high_hiv_risk ~ transgender + race + age_cat, data = filtered_data2, family = binomial)
summary(logm1)

exp(cbind(OR = coef(logm1)))

#Model 2 (Demographics and SES)
logm2 <- glm(high_hiv_risk ~ transgender + race + age_cat + income_binary + edu_binary, data = filtered_data2, family = binomial)
summary(logm2)

exp(cbind(OR = coef(logm2)))

#Model 3 (Demographics, SES, Health (confounders))
logm3 <- glm(high_hiv_risk ~ transgender + race + age_cat + income_binary + edu_binary + partnered
             + poor_health + health_plan + dr_cost
             + dr_visits + med_cost + bmi, data = filtered_data2, family = binomial)
summary(logm3)

exp(cbind(OR = coef(logm3)))

#Model 4 (demographics, ses, confounders, mediators)
logm4 <- glm(high_hiv_risk ~ transgender + race + age_cat + income_binary + edu_binary + partnered
             + poor_health + health_plan + dr_cost 
             + dr_visits + med_cost + bmi + unhealthy_drink + mental_health + smoker + sex_orient
             + physical_health, data = filtered_data2, family = binomial)
summary(logm4)

exp(cbind(OR = coef(logm4)))
```

###Natalie
```{r}
ggplot(aes(x=myass, y=git), data="lithub")
```

###Raegan
```{r}
Starting data analysis 2-14
```

###Cas
```{r}
filtered_data<-filtered_data %>%
  mutate(state = factor(x.state, levels=c(6, 9, 10, 13, 15, 16, 17, 18, 19, 21, 22, 25, 27, 28, 29, 32, 36, 39, 42, 44, 48, 50, 51, 53, 55, 66), labels=c("California", "Connecticut", "Delaware", "Georgia", "Hawaii", "Idaho", "Illinois", "Indiana", "Iowa", "Kentucky", "Louisiana", "Massachusetts", "Minnesota", "Mississippi", "Missouri", "Nevada", "New York", "Ohio", "Pennsylvania", "Rhode Island", "Texas", "Vermont", "Virginia", "Washington", "Wisconsin", "Guam"))) %>%
  mutate(generalhealth = ifelse(genhlth %in% c(7, 9), NA, genhlth)) %>%
  mutate(physicalhealth = ifelse(physhlth %in% c(77, 99), NA,
         ifelse(physhlth == 88, 0, physhlth))) %>%
  mutate(mentalhealth = ifelse(menthlth %in% c(77, 99), NA,
         ifelse(menthlth == 88, 0, menthlth))) %>%
  mutate(poorhealth = ifelse(poorhlth %in% c(77, 99), NA,
         ifelse(poorhlth == 88, 0, poorhlth))) %>%
  mutate(healthplan = ifelse(hlthpln1 == 1, "Healthcare", 
                       ifelse(hlthpln1 == 2, "No Healthcare", NA))) %>%
  mutate(medicalcost = ifelse(medcost == 1, "Cost Barrier", 
                        ifelse(medcost == 2, "No cost Barrier", NA))) %>%
  mutate(checkup = ifelse(checkup1 == 1, "<1", 
                          ifelse(checkup1 == 2, "1-2", 
                                 ifelse(checkup1 == 3, "2-5",
                                        ifelse(checkup1 == 5, ">5", NA))))) %>%
  mutate(exercise = ifelse(exerany2 == 1, "Exercise", 
                       ifelse(exerany2 == 2, "No Exercise", NA))) %>%
  mutate(sleep = ifelse(sleptim1 %in% c(77, 99), NA, sleptim1)) %>%
  mutate(sexfactor = ifelse(sex == 1, "Male", 
                       ifelse(sex == 2, "Female", "Refused"))) %>%
  mutate(educationbinary = ifelse(educa == 6, "Graduated College or Technical School", 
                                  ifelse(educa == 9, NA, "Did Not Graduate College or Technical School"))) %>%
  mutate(employment = ifelse(employ1 %in% c(1,2), "Paid Work", 
                             ifelse(employ1 %in% c(5,6), "Unpaid Work",
                                    ifelse(employ1 == 9, NA, "Not working")))) %>%
  mutate(numchildren = ifelse(children %in% c(99), NA,
         ifelse(children == 88, 0, children))) %>%
  mutate(income = ifelse(income2 %in% c(77, 99), NA, income2)) %>%
  mutate(income = factor(income, levels = c(1,2,3,4,5,6,7,8), labels = c("<10k", "10k-15k", "15k-20k", "20k-25k", "25k-35k", "35k-50k", "50k-75k", ">75k"))) %>%
  #mutate(weight = ifelse(weight2 %in% c(7777, 9999), NA,
  #                       ifelse(weight2 %in% c(9000:9998), ((weight2-9000)*2.20462), weight2)))
  #something is wrong with the weight transformation
  mutate(hivtest = ifelse(hivtst6 == 1, "Tested for HIV", 
                          ifelse(hivtst6 == 2, "Not Tested for HIV", NA))) %>%
  mutate(doctorvisits = ifelse(drvisits == 77, NA, 
                               ifelse(drvisits == 88, 0, drvisits))) %>%
  mutate(medicationcost = ifelse(medscost == 1, "Cost Barrier", 
                        ifelse(medscost == 2, "No cost Barrier",
                               ifelse(medscost == 3, "No Medication", NA)))) %>%
  mutate(sexualorientation = ifelse(sxorient == 1, "Straight",
                                    ifelse(sxorient == 2, "Lesbian or gay", 
                                           ifelse(sxorient == 3, "Bisexual", 
                                                  ifelse(sxorient == 4, "Other", NA))))) %>%
  mutate(emotionalsupport = ifelse(emtsuprt %in% c(7,9), NA, emtsuprt)) %>%
  mutate(emotionalsupport = factor(emotionalsupport, levels=c(1:5), labels=c("Always", "Usually", "Sometimes", "Rarely", "Never"))) %>%
  mutate(bmi = factor(x.bmi5cat, levels=c(1:4), labels=c("Underweight", "Normal Weight", "Overweight", "Obese"))) %>%
  mutate(racebinary = ifelse(race == "white", "White", "Non-White")) %>%
  mutate(incomebinary = ifelse(income %in% c("<10k", "10k-15k", "15k-20k", "20k-25k"), "Less than $25,000 per year", "Greater than $25,000 per year"))
```




