---
output: pdf_document
classoption: landscape
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(dplyr)
library(mosaic)
library(ggplot2)
library(stats)
library(stargazer)
library(agricolae)
library(survey)

#can't upload file because too large
#need to select vars

#vars selected and data filtered in other rmd (data download.Rmd)

filtered_data <- read.csv("Pop Health Data 2016 2.csv")
```

#CREATING NEW VARS/CLEANING
```{r, include = FALSE}
filtered_data2 <- filtered_data

#Transgender
filtered_data2 <- filtered_data2 %>%
  filter(!trnsgndr %in% c(7,9)) %>%
  mutate(transgender = ifelse(trnsgndr == 1, "female", 
                              ifelse(trnsgndr == 2, "male", 
                                     ifelse(trnsgndr == 3, "non-conforming", "cis"))))

#High HIV risk binary variable 
filtered_data2 <- filtered_data2 %>%
  filter(!is.na(hivrisk4)) %>%
  filter(!hivrisk4 %in% c(7, 9)) %>%
  mutate(high_hiv_risk = ifelse(hivrisk4 == 1, 1, 0))

#Race (grouped) 
filtered_data2 <- filtered_data2 %>%
  mutate(race = ifelse(x.racegr3 == 1, "white", 
                       ifelse(x.racegr3 == 2, "black", 
                              ifelse(x.racegr3 == 3, "other", 
                                     ifelse(x.racegr3 == 4, "multi", 
                                            ifelse(x.racegr3 == 9, NA, "hispanic"))))),
         race_binary = ifelse(x.racegr3 == 1, "white", "racial/ethnic minority"))

filtered_data2$race_binary <- as.factor(filtered_data2$race_binary)
filtered_data2$race_binary <- relevel(filtered_data2$race_binary, ref = "white")

filtered_data2$race <- as.factor(filtered_data2$race)
filtered_data2$race <- relevel(filtered_data2$race, ref = "white")

#Income (binary)
filtered_data2 <- filtered_data2 %>%
  mutate(income_binary = ifelse(income2 %in% c(1, 2, 3, 4), "<25k", 
                                ifelse(income2 %in% c(77, 99), "unknown", 
                                       ifelse(is.na(income2), NA, ">25k"))))

filtered_data2$income_binary <- as.factor(filtered_data2$income_binary)
filtered_data2$income_binary <- relevel(filtered_data2$income_binary, ref = "<25k")

#Emotional support (categorical)
filtered_data2 <- filtered_data2 %>%
  mutate(em_sup_cat = ifelse(emtsuprt %in% c(7,9), NA, emtsuprt)) %>%
  mutate(em_sup_cat = factor(emtsuprt, levels = c(1,2,3,4,5), labels = c("always", "usually", "sometimes", "rarely", "never")))

filtered_data2$em_sup_cat<- as.factor(filtered_data2$em_sup_cat)
filtered_data2$em_sup_cat <- relevel(filtered_data2$em_sup_cat, ref = "never")

#check up
filtered_data2<-filtered_data2 %>%
  mutate(checkup = ifelse(checkup1 %in% c(7,9), NA,
                          ifelse(is.na(checkup1), NA,
                                   ifelse(checkup1 == 1, "Within past year", "Not within past year"))))

filtered_data2$checkup<- as.factor(filtered_data2$checkup)
filtered_data2$checkup <- relevel(filtered_data2$checkup, ref = "Not within past year")

#Education
filtered_data2 <- filtered_data2 %>%
  mutate(edu_binary = ifelse(educa == 6, "college grad", ifelse(educa == 9, NA, "not college grad")))

filtered_data2$edu_binary<- as.factor(filtered_data2$edu_binary)
filtered_data2$edu_binary <- relevel(filtered_data2$edu_binary, ref = "not college grad")

#Age
filtered_data2 <- filtered_data2 %>%
  mutate(age_cat = factor(x.age.g, levels = c(1,2,3,4,5, 6), labels = c("18-24", "25-34", "35-44", "45-54", "55-64", "65+")))

filtered_data2$age_cat<- as.factor(filtered_data2$age_cat)
filtered_data2$age_cat <- relevel(filtered_data2$age_cat, ref = "18-24")

#Heavy Drinker
filtered_data2 <- filtered_data2 %>%
  mutate(heavy_drink = ifelse(x.rfdrhv5 == 1, "not heavy", 
                              ifelse(x.rfdrhv5 == 9, NA, "heavy drinker")))

filtered_data2$heavy_drink<- as.factor(filtered_data2$heavy_drink)
filtered_data2$heavy_drink <- relevel(filtered_data2$heavy_drink, ref = "not heavy")

#Binge Drinker
filtered_data2 <- filtered_data2 %>%
  mutate(binge_drink = ifelse(x.rfbing5 == 1, "not binge", 
                              ifelse(x.rfbing5 == 9, NA, "binge drinker")))

filtered_data2$binge_drink<- as.factor(filtered_data2$binge_drink)
filtered_data2$binge_drink <- relevel(filtered_data2$binge_drink, ref = "not binge")

#Creating unhealthy drink
filtered_data2 <- filtered_data2 %>%
  mutate(unhealthy_drink = ifelse(binge_drink == "binge drinker"|heavy_drink == "heavy drinker", "unhealthy drinker", 
                                  ifelse(is.na(binge_drink)|is.na(heavy_drink), NA, "not unhealthy")))

filtered_data2$unhealthy_drink<- as.factor(filtered_data2$unhealthy_drink)
filtered_data2$unhealthy_drink <- relevel(filtered_data2$unhealthy_drink, ref = "not unhealthy")

#Marital status
filtered_data2 <- filtered_data2 %>%
  mutate(partnered = ifelse(marital %in% c(1,6), "partnered", 
                            ifelse(marital == 9, NA, "not partnered")))

filtered_data2$partnered<- as.factor(filtered_data2$partnered)
filtered_data2$partnered <- relevel(filtered_data2$partnered, ref = "not partnered")


#General Health 
filtered_data2 <- filtered_data2 %>%
  mutate(gen_health = ifelse(genhlth %in% c(7,9), NA, genhlth)) %>%
  mutate(gen_health = factor(genhlth, levels = c(1,2,3,4,5), labels = c("excellent", "very good", "good", "fair", "poor")))

filtered_data2$gen_health<- as.factor(filtered_data2$gen_health)
filtered_data2$gen_health <- relevel(filtered_data2$gen_health, ref = "poor")

#physical health
filtered_data2 <- filtered_data2 %>%
  mutate(physical_health = ifelse(physhlth == 88, 0, 
                                  ifelse(physhlth %in% c(77, 99), NA, physhlth)))

#mental health
filtered_data2 <- filtered_data2 %>%
  mutate(mental_health = ifelse(menthlth == 88, 0, 
                                ifelse(menthlth %in% c(77, 99), NA, menthlth)))

#poor health
# filtered_data2 <- filtered_data2 %>%
#   mutate(poor_health = ifelse(is.na(poor_health), 0, 
#                           ifelse(poorhlth == 88, 0, 
#                                 ifelse(poorhlth %in% c(77, 99), NA, poorhlth))))

#health plan
filtered_data2 <- filtered_data2 %>%
  mutate(health_plan = ifelse(hlthpln1 == 1, "health care", 
                              ifelse(hlthpln1 %in% c(7,9), NA, "no health care")))

filtered_data2$health_plan<- as.factor(filtered_data2$health_plan)
filtered_data2$health_plan <- relevel(filtered_data2$health_plan, ref = "no health care")

#medical cost
filtered_data2 <- filtered_data2 %>%
  mutate(dr_cost = ifelse(medcost == 1, "could not afford", 
                          ifelse(medcost %in% c(7,9), NA, "always afford")))

filtered_data2$dr_cost<- as.factor(filtered_data2$dr_cost)
filtered_data2$dr_cost <- relevel(filtered_data2$dr_cost, ref = "could not afford")

#routine checkup
# filtered_data2 <- filtered_data2 %>%
#   mutate(routine_checkup = ifelse(checkup1 == 1, "past year", ifelse(checkup1 == 2, "past 2 years", ifelse(checkup1 == 3, "past 5 years", ifelse(checkup1 == 4, "5 or more years", ifelse(checkup1 %in% c(7,9), NA, "Never"))))))
# 
# filtered_data2$routine_checkup<- as.factor(filtered_data2$routine_checkup)
# filtered_data2$routine_checkup <- relevel(filtered_data2$routine_checkup, ref = "Never")

#sexual orientation
filtered_data2 <- filtered_data2 %>%
  mutate(sex_orient = ifelse(sxorient %in% c(7,9), NA, sxorient)) %>%
  mutate(sex_orient = factor(sxorient, levels = c(1,2,3,4), labels = c("straight", "lesbian/gay", "bisexual", "other")))

filtered_data2$sex_orient<- as.factor(filtered_data2$sex_orient)
filtered_data2$sex_orient <- relevel(filtered_data2$sex_orient, ref = "straight")


#doctor visits
filtered_data2 <- filtered_data2 %>%
  mutate(dr_visits = ifelse(is.na(drvisits), 0, 
                                ifelse(drvisits == 88, 0,  
                                       ifelse(drvisits %in% c(77, 99), NA, drvisits))))

#medication cost
filtered_data2 <- filtered_data2 %>%
  mutate(med_cost = ifelse(is.na(medscost), "unknown",
                        ifelse(medscost == 1, "could not afford",
                           ifelse(medscost == 2, "always afford", 
                                  ifelse(medscost == 3, "no medicine prescribed", "unknown")))))

filtered_data2$med_cost<- as.factor(filtered_data2$med_cost)
filtered_data2$med_cost <- relevel(filtered_data2$med_cost, ref = "could not afford")

#BMI 
filtered_data2 <- filtered_data2 %>%
  mutate(bmi = factor(x.bmi5cat, levels = c(1,2,3,4), labels = c("underweight", "normal", "overweight", "obese")),
         bmi_2 = ifelse(is.na(x.bmi5cat), "unknown", bmi))

filtered_data2$bmi<- as.factor(filtered_data2$bmi)
filtered_data2$bmi <- relevel(filtered_data2$bmi, ref = "normal")

#Smoking
filtered_data2 <- filtered_data2 %>%
  mutate(smoker = ifelse(x.smoker3 == 9, NA,
                         ifelse(x.smoker3 %in% c(1, 2, 3), "has smoked", "never smoked")))

filtered_data2$smoker<- as.factor(filtered_data2$smoker)
filtered_data2$smoker <- relevel(filtered_data2$smoker, ref = "never smoked")
```

#CREATING THE MODELS
```{r, include = FALSE}
########MODELS

#simple model
log_simp <- glm(high_hiv_risk ~ transgender, data = filtered_data2, family = binomial)
summary(log_simp)

exp(cbind(OR = coef(log_simp)))

#Risk Difference
RD_crude<- glm(high_hiv_risk ~ transgender, data=filtered_data2, family=gaussian(link="identity"))
summary(RD_crude)
confint(RD_crude)

#Model 1 (Demographics)
logm1 <- glm(high_hiv_risk ~ transgender + race + age_cat, data = filtered_data2, family = binomial)
summary(logm1)

exp(cbind(OR = coef(logm1)))

#Model 2 (Demographics and SES)
logm2 <- glm(high_hiv_risk ~ transgender + race + age_cat + income_binary + edu_binary, data = filtered_data2, family = binomial)
summary(logm2)

exp(cbind(OR = coef(logm2)))

#Model 3 (Demographics, SES, Health (confounders))
logm3 <- glm(high_hiv_risk ~ transgender + race + age_cat + income_binary + edu_binary + partnered
             + health_plan + dr_cost + checkup
             + med_cost + bmi, data = filtered_data2, family = binomial)
summary(logm3)

exp(cbind(OR = coef(logm3)))

#Model 4 (demographics, ses, confounders, mediators)
logm4 <- glm(high_hiv_risk ~ transgender + race + age_cat + income_binary + edu_binary + partnered
             + health_plan + dr_cost + checkup
             + med_cost + bmi + unhealthy_drink + mental_health + smoker + sex_orient
             + physical_health, data = filtered_data2, family = binomial)
summary(logm4)

exp(cbind(OR = coef(logm4)))
```

#CREATING STARGAZER TABLE OF LOGM4
```{r mylatextable3, results = "asis"}
stargazer(logm1, logm2, logm3, logm4, type = "latex",
          ci=TRUE, ci.level=0.95, digits = 2,
          title= "The odds ratios (OR) and 95% confidence intervals (CI) of HIV Risk Behaviors in relation to Gender Identity, BRFSS (2014-2016)",
          covariate.labels= c("Transgender Women", "Transgender Men", "GNC",
                               "Race: Black", "Race: Hispanic", "Race: Multi", "Race: Other",
                              "Age: 25-34", "Age: 35-44", "Age: 45-54", "Age: 55-64",
                              "Age: 65+", "Income: 25k+", "Income unknown", "College Grad", "Partnered",
                              "Health Care", "Always Afford Dr",
                              "Checkup within past year", "Always Afford Meds", "No meds prescribed", "Meds: unknown", "BMI: Underweight",
                              "BMI: Overweight", "BMI: Obese", "No unhealthy Drinking",
                              "Mental Health", "Has Smoked", "SO: Lesbian/Gay",
                              "SO: Bisexual", "SO: Other", "Physical Health"),
          dep.var.caption= "Dependent Variable",
          dep.var.labels= "High HIV Risk",
          single.row = TRUE,
          column.labels = c("Demographics", "SES", "Confounders", "Mediators"),
          font.size= 'small',
          apply.coef=exp,
          t.auto=F,
          p.auto=F)

```

#CREATING STARGAZER TABLE OF RISK DIFFERENCE
```{r mylatextable4, results = "asis"}
stargazer(RD_crude, type = "latex",
          ci=TRUE, ci.level=0.95, digits = 3,
          title= "The Risk Differences (RD) and 95% confidence intervals (CI) of HIV Risk Behaviors in relation to Gender Identity, BRFSS (2014-2016)",
          single.row = TRUE,
          dep.var.caption= "Dependent Variable",
          dep.var.labels= "High HIV Risk",
          covariate.labels= c("Trans-Women", "Trans-Men", "GNC"))

```

#Anova and FLSD
```{r, include = FALSE}
anova(log_simp, test = "Chisq")

anova(logm1, test = "Chisq")
LSD1<-LSD.test(logm1,"transgender", group=TRUE, console=TRUE)

anova(logm2, test = "Chisq")
LSD1<-LSD.test(logm2,"transgender", group=TRUE, console=TRUE)

anova(logm3, test = "Chisq")
LSD1<-LSD.test(logm3,"transgender", group=TRUE, console=TRUE)

#WHAT WE ACTUALLY WANT TO TEST
anova(logm4, test = "Chisq")

LSD1<-LSD.test(logm4,"transgender", group=TRUE, console=TRUE)
plot(LSD1)
```